#!/bin/sh

# Obtener la versión actual del package.json
CURRENT_VERSION=$(node -p "require('./package.json').version")

# Incrementar la versión en el package.json utilizando npm version (incremento de parche)
npx npm version patch --no-git-tag-version

# Obtener la nueva versión después de la actualización
NEW_VERSION=$(node -p "require('./package.json').version")

# Verificar si la versión ha cambiado
if [ "$CURRENT_VERSION" = "$NEW_VERSION" ]; then
  echo "Error: La versión en el package.json debe ser diferente al commit anterior."
  exit 1
fi
