#!/bin/sh

# Obtener la versión actual del package.json
CURRENT_VERSION=$(node -p "require('./package.json').version")

# Actualizar la versión en el package.json utilizando npm version (incremento de parche)
npm version patch

# Obtener la nueva versión después de la actualización
NEW_VERSION=$(node -p "require('./package.json').version")

# Verificar si la versión ha cambiado
if [ "$CURRENT_VERSION" = "$NEW_VERSION" ]; then
  echo "Error: The current version cannot be the same as the new version."
  exit 1
fi
